name: Release Assets

on:
  push:
    tags:
      - v1.**

jobs:
  publish-assets:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        curl -o composer.phar -L https://getcomposer.org/composer-stable.phar
        php composer.phar install --no-ansi --no-interaction --no-dev

    - name: Clean up project
      run: |
        rm -rf .git* .vscode
        rm -f composer.phar

    - name: Build archive
      run: zip -r /tmp/phproject-${{ github.ref_name }}.zip "$GITHUB_WORKSPACE"

    - name: Upload archive
      uses: softprops/action-gh-release@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        files: |
          /tmp/phproject-${{ github.ref_name }}.zip
